-- 1. TABELA DE CLIENTES
CREATE TABLE CLIENTE 
(
    ID_CLIENTE 		INT,
    NOME 			VARCHAR(200) NOT NULL,
    CPF_CNPJ 		VARCHAR(14) NOT NULL
);

ALTER TABLE CLIENTE ADD
	CONSTRAINT PK_CLIENTE
	PRIMARY KEY (ID_CLIENTE);

-- 2. TABELA DE CARROS
CREATE TABLE CARRO 
(
    ID_CARRO 		INT,
    MODELO 			VARCHAR(50) NOT NULL,
    ANO_LANCAMENTO 	INT NOT NULL
);

ALTER TABLE CARRO ADD
	CONSTRAINT PK_CARRO
	PRIMARY KEY (ID_CARRO);

-- 3. TABELA DE VENDAS
CREATE TABLE VENDA 
(
    ID_VENDA 		INT,
    ID_CLIENTE 		INT NOT NULL,
    ID_CARRO 		INT NOT NULL,
    DATA_VENDA 		DATE NOT NULL
);

ALTER TABLE VENDA ADD
	CONSTRAINT PK_VENDA
	PRIMARY KEY (ID_VENDA);

ALTER TABLE VENDA ADD
	CONSTRAINT FK_VENDA_CLIENTE
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE VENDA ADD
	CONSTRAINT FK_VENDA_CARRO
	FOREIGN KEY (ID_CARRO) REFERENCES CARRO(ID_CARRO);