SELECT 
    CLI.ID_CLIENTE,
    CLI.NOME,
    COUNT(V.ID_VENDA) AS QTD_VENDAS_UNO
FROM 
	CLIENTE CLI
	LEFT JOIN VENDA V ON CLI.ID_CLIENTE = V.ID_CLIENTE
	LEFT JOIN CARRO CAR ON V.ID_CARRO = CAR.ID_CARRO AND UPPER(CAR.MODELO) = 'UNO'
GROUP BY 
	CLI.ID_CLIENTE, 
	CLI.NOME
HAVING COUNT(V.ID_VENDA) > 0;