SELECT 
	COUNT(*) AS TOTAL_CLIENTES_SEM_COMPRAS
FROM 
	CLIENTE CLI
WHERE 
	NOT EXISTS (
					SELECT 
						1 
					FROM 
						VENDA V 
					WHERE 
						V.ID_CLIENTE = CLI.ID_CLIENTE
				);