SELECT 
    CLI.ID_CLIENTE,
    CLI.NOME,
    CLI.CPF_CNPJ,
    V.DATA_VENDA,
    CAR.MODELO,
    CAR.ANO_LANCAMENTO
FROM 
	VENDA V
	INNER JOIN CLIENTE CLI ON V.ID_CLIENTE = CLI.ID_CLIENTE
	INNER JOIN CARRO CAR ON V.ID_CARRO = CAR.ID_CARRO
WHERE 
	UPPER(CAR.MODELO) = 'MAREA'
	AND CAR.ANO_LANCAMENTO = 2021
	AND CLI.CPF_CNPJ LIKE '0%'
	-- DESCLASSIFICA CLIENTES QUE COMPRARAM 2 OU MAIS MAREAS
	AND CLI.ID_CLIENTE NOT IN (
								SELECT 
									V_SUB.ID_CLIENTE
								FROM 
									VENDA V_SUB
									INNER JOIN CARRO C_SUB ON V_SUB.ID_CARRO = C_SUB.ID_CARRO
								WHERE 
									UPPER(C_SUB.MODELO) = 'MAREA'
								GROUP BY 
									V_SUB.ID_CLIENTE
								HAVING COUNT(*) >= 2
							  )
ORDER BY 
	V.DATA_VENDA ASC
FETCH FIRST 15 ROWS ONLY;